services:
  backend:
    build:
      context: ./backend
    container_name: simulacao-energia-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - simulacao-net
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=simulacao_energia
    depends_on:
      - postgres
    command: npm start

  frontend:
    build:
      context: ./meu-projeto-frontend
    container_name: simulacao-energia-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./meu-projeto-frontend:/usr/src/app
    networks:
      - simulacao-net

  postgres:
    image: postgres:latest
    container_name: simulacao-energia-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: simulacao_energia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - simulacao-net

volumes:
  postgres_data:

networks:
  simulacao-net:
    driver: bridge

