services:
  backend:
    build:
      context: ./backend
    container_name: simulacao-energia-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - simulacao-net
    environment:
      - MONGO_URL=mongodb://mongo:27017/simulacao_energia
    depends_on:
      - mongo
    command: npm start

  frontend:
    build:
      context: ./meu-projeto-frontend
    container_name: simulacao-energia-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./meu-projeto-frontend:/usr/src/app
    networks:
      - simulacao-net

  mongo:
    image: mongo:latest
    container_name: simulacao-energia-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - simulacao-net

networks:
  simulacao-net:
    driver: bridge

volumes:
  mongo_data:
